# This is a basic workflow to help you get started with Actions

name: Sample Book Application Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "github_workflows"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: X64
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Building of node application is satrting.."
      - name: Install all depentdencies
        run: npm install

  deploy-dev:
    runs-on: X64
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to DEV has started.."
      - name: Install all depentdencies
        run: npm install
      - name: Delete existing pm2 service
        run: pm2 delete "books-DEV" || exit 0
      - name: Run sample-book-app pm2 service
        run: pm2 start -n "books-DEV" index.js -- 1010"

  test-dev:
    runs-on: X64
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
        with:
            repository: "GirtsMs/api-automation"
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started.."
      - name: Install all depentdencies
        run: npm install
      - name: Run API tests
        run: npm run BOOKS BOOKS_DEV

  deploy-stg:
    runs-on: X64
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to STG has started.."

  test-stg:
    runs-on: X64
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started.."

  deploy-prd:
    runs-on: X64
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to PRD has started.."

  test-prd:
    runs-on: X64
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started.."
