# This is a basic workflow to help you get started with Actions

name: Sample Book Application Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "github_workflows"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'DEV'
          port: '1010'

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'DEV'
          test-suite: 'BOOKS'

  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'STG'
          port: '2020'

  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'DEV'
          test-suite: 'BOOKS'

  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'PRD'
          port: '3030'

  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: 'DEV'
          test-suite: 'BOOKS'
