# This is a basic workflow to help you get started with Actions

name: Sample Book Application Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "github_workflows"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Building of node application is satrting.."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to DEV has started.."

  test-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started.."

  deploy-stg:
    runs-on: ubuntu-latest
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to STG has started.."

  test-stg:
    runs-on: ubuntu-latest
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started.."

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Deployment to PRD has started.."

  test-prd:
    runs-on: ubuntu-latest
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started.."
